CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000),
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    initiator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    published_on TIMESTAMP WITHOUT TIME ZONE,
    confirmed_requests INTEGER NOT NULL DEFAULT 0,
    rating_score BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value IN (-1, 1)),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(event_id, user_id)
);

DELETE FROM ratings WHERE id < 100000;
DELETE FROM participation_requests WHERE id < 100000;
DELETE FROM compilation_events WHERE compilation_id < 100000 OR event_id < 100000;
DELETE FROM compilations WHERE id < 100000;
DELETE FROM events WHERE id < 100000;
DELETE FROM categories WHERE id < 100000;
DELETE FROM users WHERE id < 100000;

INSERT INTO users (id, name, email, created_on) VALUES
(100101, 'Инициатор события для тестирования рейтингов', 'initiator-rating-test-high@test.com', NOW() - INTERVAL '2 days'),
(100102, 'Участник события для тестирования рейтингов', 'participant-rating-test-high@test.com', NOW() - INTERVAL '2 days'),
(100103, 'Не участник для тестирования рейтингов', 'non-participant-rating-test-high@test.com', NOW() - INTERVAL '2 days'),
(100104, 'Второй участник для тестов доступа рейтингов', 'second-participant-rating-test-high@test.com', NOW() - INTERVAL '2 days')
ON CONFLICT (id) DO NOTHING;

INSERT INTO categories (id, name) VALUES
(100051, 'Концерты для тестирования рейтингов (высокий ID)')
ON CONFLICT (id) DO NOTHING;

INSERT INTO events (
    id,
    title,
    annotation,
    description,
    category_id,
    event_date,
    lat,
    lon,
    paid,
    participant_limit,
    request_moderation,
    state,
    initiator_id,
    confirmed_requests,
    rating_score,
    created_on
) VALUES (
    100201,
    'Прошедший концерт для тестирования рейтингов (высокий ID)',
    'Аннотация тестового события которое уже прошло для проверки работы системы оценок и рейтингов более двадцати символов обязательно',
    'Полное описание тестового события созданного специально для тестирования функционала лайков и дизлайков участниками завершенных мероприятий более двадцати символов',
    100051,
    NOW() - INTERVAL '1 day',
    55.754167,
    37.62,
    false,
    10,
    true,
    'PUBLISHED',
    100101,
    2,
    0,
    NOW() - INTERVAL '2 days'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO events (
    id,
    title,
    annotation,
    description,
    category_id,
    event_date,
    lat,
    lon,
    paid,
    participant_limit,
    request_moderation,
    state,
    initiator_id,
    confirmed_requests,
    rating_score,
    created_on
) VALUES (
    100202,
    'Будущий концерт для тестирования валидации рейтингов (высокий ID)',
    'Аннотация будущего концерта созданного для тестирования валидации более двадцати символов длинная',
    'Описание будущего концерта для проверки что нельзя оценить незавершенное событие более двадцати символов',
    100051,
    NOW() + INTERVAL '2 days',
    55.75,
    37.63,
    false,
    5,
    true,
    'PUBLISHED',
    100101,
    1,
    0,
    NOW() - INTERVAL '1 day'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO participation_requests (id, event_id, requester_id, status, created) VALUES
(100301, 100201, 100102, 'CONFIRMED', NOW() - INTERVAL '1 day'),
(100302, 100202, 100102, 'CONFIRMED', NOW() - INTERVAL '12 hours'),
(100303, 100201, 100104, 'CONFIRMED', NOW() - INTERVAL '1 day')
ON CONFLICT (id) DO NOTHING;

INSERT INTO ratings (id, event_id, user_id, value, created_at) VALUES
(100401, 100201, 100102, 1, NOW() - INTERVAL '6 hours'),
(100402, 100201, 100104, -1, NOW() - INTERVAL '3 hours')
ON CONFLICT (id) DO NOTHING;